"""property upfront costs and deal files

Revision ID: 376f64b9c765
Revises: 3025c8f4adde
Create Date: 2026-09-27 13:55:46.693641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '376f64b9c765'
down_revision: Union[str, None] = '3025c8f4adde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deal_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deal_id', sa.Integer(), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('stored_name', sa.String(length=255), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['deal_id'], ['wholesale_deals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('deal_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deal_files_deal_id'), ['deal_id'], unique=False)

    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('taxes_at_closing', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('insurance_at_closing', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.drop_column('insurance_at_closing')
        batch_op.drop_column('taxes_at_closing')

    with op.batch_alter_table('deal_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deal_files_deal_id'))

    op.drop_table('deal_files')
    # ### end Alembic commands ###
